/**
 * @module harness/scene
 * @description The dialogue architecture from `.llm/fiction-context-design.md` §5:
 * one call per speaker, a bid every round, an arbiter, a Director off the
 * critical path, and a narration pass over what was committed.
 *
 * The claim being tested: a model writing both sides of an argument in one
 * pass has perfect information on both sides, and every failure of its
 * dialogue follows from that — the call-and-response ladder, the shared
 * vocabulary, the joke that lands. So each speaker is generated by its own
 * call that knows its own objective and nothing of the other's.
 *
 * What each call may see is the experiment, so it is enforced here rather than
 * asked for: `speakerMessages` takes one speaker's sketch, objective, belief,
 * the props, and the transcript. There is no argument it could pass that would
 * put the other speaker's objective in front of it.
 *
 * Separate from `dialogue.js` so that one stage of it can be imported and
 * probed on its own. Importing a command-line module runs the command.
 */

import { complete } from './wire.js'

/**
 * @typedef {Object} Speaker
 * @property {string} id
 * @property {string} name - What the transcript calls them
 * @property {string} sketch - Behavioural sketch, prose
 * @property {string} objective - What they want in this conversation, now
 * @property {string} belief - Their read on the other, as belief rather than fact
 *
 * @typedef {Object} Turn
 * @property {number} n
 * @property {string} speaker - Speaker id
 * @property {string} line
 * @property {string} [action]
 * @property {boolean} [silence] - This person was addressed and said nothing
 * @property {string} objectiveAtTime - What they were pursuing, for reading back
 *
 * @typedef {Object} Bid
 * @property {string} speaker
 * @property {boolean} pass
 * @property {string} [line]
 * @property {string} [action]
 * @property {string} [reasoning]
 * @property {number} ms
 * @property {number} tokens
 *
 * @typedef {Object} SceneState
 * @property {Turn[]} turns
 * @property {Record<string, Speaker>} speakers
 * @property {string[]} props
 * @property {string} setting - One line, what the room is
 * @property {boolean} directorRunning
 * @property {any[]} log - Every round: the bids, who won, what the Director said
 */

/** How many exchanges a speaker sees. Positioned last, closest to generation. */
const TRANSCRIPT_WINDOW = 8

/** Committed turns between Director runs. */
export const DIRECT_EVERY = 5

/**
 * The rules every speaker call carries. Shape constraints, not phrase bans:
 * the one thing a speaker call must not be able to do is write a dialogue tag,
 * because that is where the adverbs live.
 */
const SPEAKER_RULES = `Rules: 1-3 lines. No names in address. Don't explain yourself.
Physical action allowed, on its own line as (action: ...). No interiority. No dialogue tags.
Output the line only, with no name in front of it.
Silence is a real move and it is available every round. If this person would let the other one fill it — because they are waiting, because answering is what the other wants, because there is nothing to say that helps — reply with exactly PASS.`

/**
 * The messages for one speaker's turn.
 *
 * Everything this speaker may know, and nothing else: their own sketch,
 * objective and belief, the props, and the transcript. The other's objective
 * is not a parameter here, which is the point.
 *
 * @param {Speaker} speaker
 * @param {SceneState} state
 * @returns {Array<{role: string, content: string}>}
 */
export function speakerMessages(speaker, state) {
  const transcript = state.turns
    .slice(-TRANSCRIPT_WINDOW)
    .map(turn => {
      const who = state.speakers[turn.speaker]?.name || turn.speaker
      if (turn.silence) return `(${who.toUpperCase()} ${turn.action || 'says nothing'}.)`
      const action = turn.action ? `\n(${turn.action})` : ''
      return `${who.toUpperCase()}: ${turn.line}${action}`
    })
    .join('\n')

  const system = `You are writing one line of dialogue for ${speaker.name}, and nothing else.

${speaker.sketch}

Right now ${speaker.name} wants: ${speaker.objective}
${speaker.name} thinks: ${speaker.belief}

Where this is happening: ${state.setting}
In reach: ${state.props.join(', ')}

${SPEAKER_RULES}`

  const user = transcript
    ? `${transcript}\n\n${speaker.name.toUpperCase()}:`
    : `Nothing has been said yet. ${speaker.name.toUpperCase()}:`

  return [
    { role: 'system', content: system },
    { role: 'user', content: user },
  ]
}

/**
 * Read a speaker call's answer.
 *
 * Models put the name back on the front however often they are told not to, so
 * that is stripped rather than counted against the line. Anything in
 * parentheses on its own is an action whether or not it arrived in the
 * requested shape, and one speaker quoting its own dialogue while the other
 * does not is a formatting difference the transcript should not carry into
 * the next call.
 *
 * Anything that still looks like a dialogue tag is left alone and shows up in
 * the scoring, where it is evidence rather than a bug.
 *
 * @param {string} raw
 * @param {Speaker} speaker
 * @returns {{pass: boolean, line?: string, action?: string}}
 */
export function parseBid(raw, speaker) {
  let text = raw.trim()

  const name = speaker.name.toUpperCase()
  text = text.replace(new RegExp(`^${name}\\s*:\\s*`, 'i'), '').trim()

  // Before anything else, take off the wrapping the model adds on its own —
  // quotation marks, bold, a trailing full stop. A refusal to speak came back
  // as `"PASS"` once and was committed as a line of dialogue reading PASS,
  // which is the whole scene's worth of damage from one pair of quotes.
  const unwrapped = text
    .replace(/^[*_"“'`]+/, '')
    .replace(/[*_"”'`.]+$/, '')
    .trim()
  if (/^pass$/i.test(unwrapped)) return { pass: true }

  /** @type {string[]} */
  const actions = []
  const takeAction = (/** @type {string} */ act) => {
    actions.push(act.replace(/^action:\s*/i, '').trim())
    return ''
  }

  // A parenthetical on its own line, wherever it sits, is a beat rather than
  // something spoken. Asking for `(action: ...)` gets it about half the time.
  text = text
    .split('\n')
    .map(line => {
      const whole = line.trim().match(/^\((.+)\)$/)
      return whole ? takeAction(whole[1]) : line
    })
    .join('\n')
    .replace(/\(\s*action:\s*([^)]*)\)/gi, (_, act) => takeAction(act))
    .trim()

  // One speaker came back quoting itself and the other did not, which reads as
  // two conventions in one transcript. The quotes are the model's, not the
  // line's, so they come off.
  const quoted = text.match(/^["“](.+)["”]$/s)
  if (quoted && !/["“]/.test(quoted[1])) text = quoted[1].trim()

  const action = actions.length > 0 ? actions.join('; ') : undefined
  if (!text) return action ? { pass: false, line: '', action } : { pass: true }
  return action ? { pass: false, line: text, action } : { pass: false, line: text }
}

/**
 * Which bid gets the beat.
 *
 * Deliberately not a model call: it sits on the critical path and it is a coin
 * flip dressed as a decision. Whoever did not speak last, and failing that
 * whoever was asked something.
 *
 * @param {Bid[]} live - Bids that are not passes
 * @param {SceneState} state
 * @returns {Bid}
 */
export function arbitrate(live, state) {
  if (live.length === 1) return live[0]

  // Whoever did not speak last. With two speakers that is the whole rule —
  // the design note's tie-break toward whoever was addressed only decides
  // anything once there are three people who could all answer.
  const last = state.turns[state.turns.length - 1]
  const other = last && live.find(bid => bid.speaker !== last.speaker)
  if (other) return other

  return live[Math.floor(Math.random() * live.length)]
}

/**
 * One round: every speaker bids at once, one is committed.
 *
 * The calls are concurrent because they do not depend on each other — which is
 * the same reason the dialogue works, so it costs nothing to say twice.
 *
 * @param {SceneState} state
 * @param {{endpoint: any, model: string, thinking: boolean, silence?: boolean}} opts
 * @returns {Promise<{turn: Turn|null, bids: Bid[]}>}
 */
export async function nextTurn(state, opts) {
  const speakers = Object.values(state.speakers)
  const spoken = state.turns.filter(turn => !turn.silence)
  const last = spoken[spoken.length - 1]
  const bids = await Promise.all(
    speakers.map(async speaker => {
      try {
        const answer = await complete({
          endpoint: opts.endpoint,
          model: opts.model,
          messages: speakerMessages(speaker, state),
          thinking: opts.thinking,
          maxTokens: 300,
          overrides: { parameters: { temperature: 1.0 } },
        })
        const parsed = parseBid(answer.content, speaker)
        return {
          speaker: speaker.id,
          ...parsed,
          reasoning: answer.reasoning,
          ms: answer.ms,
          tokens: answer.usage.completion,
        }
      } catch (error) {
        return { speaker: speaker.id, pass: true, error: String(error), ms: 0, tokens: 0 }
      }
    })
  )

  // A bid can be a beat with no words. Asked to say nothing, the model is as
  // likely to answer "(goes quiet)" as PASS, and that is a better answer: it
  // is the silence *and* what the silence looked like. Dropping it for having
  // no line would throw away the one move Noah's sketch is built on.
  const live = bids.filter(bid => !bid.pass && (bid.line || bid.action))
  if (live.length === 0) return { turn: null, bids }

  // A pass by whoever just spoke changes nothing — they had their line, and
  // the beat was going to the other person anyway. It is a pass by the person
  // who was *just addressed* that means something, and unless it is recorded
  // it is invisible: the arbiter simply hands the beat back to the speaker and
  // the transcript reads as though nobody declined anything. So it becomes a
  // turn of its own, which the next round's calls can see and answer.
  const due = last ? speakers.find(speaker => speaker.id !== last.speaker) : null
  const dueBid = due && bids.find(bid => bid.speaker === due.id)
  const alreadySilent = state.turns[state.turns.length - 1]?.silence
  if (opts.silence !== false && due && dueBid?.pass && !alreadySilent) {
    return {
      turn: {
        n: state.turns.length + 1,
        speaker: due.id,
        line: '',
        silence: true,
        objectiveAtTime: due.objective,
      },
      bids,
    }
  }

  const won = arbitrate(live, state)
  /** @type {Turn} */
  const turn = {
    n: state.turns.length + 1,
    speaker: won.speaker,
    line: won.line || '',
    ...(won.action ? { action: won.action } : {}),
    ...(won.line ? {} : { silence: true }),
    objectiveAtTime: state.speakers[won.speaker].objective,
  }
  return { turn, bids }
}

/**
 * The Director: objective maintenance, and nothing else.
 *
 * Not scene planning. A speaker pursuing an objective the scene has already
 * settled is how this produces four exchanges of nothing, and that is the one
 * failure it exists to catch.
 *
 * @param {SceneState} state
 * @param {{endpoint: any, model: string}} opts
 * @returns {Promise<{updates: Record<string, {objective?: string, belief?: string}>, raw: string, ms: number}>}
 */
export async function runDirector(state, opts) {
  const transcript = state.turns
    .map(turn => `${state.speakers[turn.speaker].name.toUpperCase()}: ${turn.line}`)
    .join('\n')

  const roster = Object.values(state.speakers)
    .map(
      speaker =>
        `${speaker.id} (${speaker.name})\n  wants: ${speaker.objective}\n  thinks: ${speaker.belief}`
    )
    .join('\n')

  const system = `You direct a scene from outside it. You do not write dialogue and you never speak to the characters.

Each person in the scene is pursuing one objective, and holds one belief about the other. Your only job is to say whether each objective still holds, and to rewrite the ones that do not.

There are two ways an objective goes wrong, and the second is the one that gets missed.

The first: the scene has settled it. They got what they wanted, or it became impossible, or they have plainly stopped trying.

The second: it is still live, still unmet, and no longer producing anything. Read the last five lines and ask what changed — what either person now knows, has, or has given up that they did not have five lines ago. If the answer is nothing, the scene is circling, and it circles precisely because both objectives are intact and neither can be reached by saying another version of the same thing. An objective that has generated five lines of the same move is as stale as one that has been met, whatever it still says.

Either way, replace it with something concrete that can succeed or fail within a few exchanges and that follows from what has just happened. Prefer an objective that makes someone do something rather than say something. Do not simply restate the objective in new words: if you are not changing what it makes them do, leave it alone and change nothing.

Keep the constraint. An objective that says how something may not be done — without being the one who suggests it, without saying the word, without leaving the room — is carrying the whole character, and an objective that drops it is a different person wanting the same thing. Rewrite what they are going for; carry the constraint across untouched.

A belief is that person's read on the other, and it is allowed to be wrong. Update it only when the scene has shown them something that would change it.

Reply with JSON and nothing else:
{"moved": "<what changed in the last five lines, or 'nothing'>", "<id>": {"objective": "...", "belief": "..."}}
Always include "moved". Include a person only when you are changing their objective or belief.`

  const user = `The people:\n${roster}\n\nWhat has been said:\n${transcript}`

  const answer = await complete({
    endpoint: opts.endpoint,
    model: opts.model,
    messages: [
      { role: 'system', content: system },
      { role: 'user', content: user },
    ],
    thinking: true,
    // The Director thinks for two to three thousand tokens before it writes
    // three short strings, and a budget that runs out mid-thought returns
    // empty content rather than a short answer. Three runs of this were read
    // as the Director declining to change anything; it never got to speak.
    maxTokens: 4000,
  })

  /** @type {Record<string, any>} */
  let updates = {}
  const json = answer.content.match(/\{[\s\S]*\}/)
  if (json) {
    try {
      updates = JSON.parse(json[0])
    } catch {
      updates = {}
    }
  }
  return { updates, raw: answer.content, finish: answer.finish, ms: answer.ms }
}

/**
 * Fire the Director if it is due and not already running, and write what it
 * says back whenever it lands. Nothing waits on it.
 *
 * @param {SceneState} state
 * @param {{endpoint: any, model: string}} opts
 */
function maybeDirect(state, opts) {
  if (state.directorRunning) return
  if (state.turns.length === 0 || state.turns.length % DIRECT_EVERY !== 0) return
  state.directorRunning = true
  const at = state.turns.length
  runDirector(state, opts)
    .then(({ updates, raw, finish, ms }) => {
      for (const [id, update] of Object.entries(updates)) {
        if (id === 'moved') continue
        const speaker = state.speakers[id]
        if (!speaker) continue
        if (update.objective) speaker.objective = update.objective
        if (update.belief) speaker.belief = update.belief
      }
      state.log.push({
        director: { afterTurn: at, landedAfter: state.turns.length, updates, raw, finish, ms },
      })
    })
    .catch(error => {
      state.log.push({ director: { afterTurn: at, error: String(error) } })
    })
    .finally(() => {
      state.directorRunning = false
    })
}

/**
 * Render the committed turns as manuscript prose.
 *
 * Run once, at the end, over what was actually said. The constraints here are
 * the ones the transcript rounds established: the sketches are the writer's,
 * not the reader's, and nothing says how a line sounded.
 *
 * @param {SceneState} state
 * @param {{endpoint: any, model: string, narration: string}} opts
 * @returns {Promise<{prose: string, finish: string, ms: number}>}
 */
export async function narrate(state, opts) {
  const transcript = state.turns
    .map(turn => {
      const who = state.speakers[turn.speaker].name.toUpperCase()
      if (turn.silence) return `(${who} ${turn.action || 'says nothing'}.)`
      return turn.action ? `${who}: ${turn.line}\n(${turn.action})` : `${who}: ${turn.line}`
    })
    .join('\n')

  const system = `You are rendering a recorded exchange as finished prose.

${opts.narration}

The lines are fixed. Keep them, in order, with their wording. What you add is what is between them: the beats, the physical business, what the point-of-view character does while the other is talking. Cut nothing and invent no new dialogue.

Where the record says someone says nothing, that silence is part of the scene and stays where it is. Give it a beat. Do not fill it with a line.

Where this happens: ${state.setting}
In reach: ${state.props.join(', ')}

Never say how a line sounds — no adverb on a tag, and no sentence after a line about a voice, a tone, or a face. Most lines need no tag at all. Never explain what a line or a gesture means. Temperature and weather enter only through what they do to objects and what they stop someone doing, never described directly and never by simile.`

  const answer = await complete({
    endpoint: opts.endpoint,
    model: opts.model,
    messages: [
      { role: 'system', content: system },
      { role: 'user', content: transcript },
    ],
    thinking: true,
    // Sixteen lines of transcript plus the beats between them, after a
    // reasoning block. At 2,000 one run stopped mid-sentence — "Riley put a
    // hand flat" — and dropped the last four lines of the scene, which read as
    // a bad narration pass rather than as a truncated one.
    maxTokens: 6000,
  })
  return { prose: answer.content, finish: answer.finish, ms: answer.ms }
}

/**
 * Run a scene to its cap or until everybody passes.
 *
 * A round where nobody bids is silence, and silence is the thing a generation
 * call cannot produce on its own — so it ends the scene rather than being
 * retried.
 *
 * @param {any} spec - Scene spec, already read
 * @param {{endpoint: any, model: string, thinking: boolean, turns: number, silence?: boolean, onRound?: (round: any) => void}} opts
 * @returns {Promise<SceneState>}
 */
export async function runScene(spec, opts) {
  /** @type {SceneState} */
  const state = {
    turns: [],
    speakers: JSON.parse(JSON.stringify(spec.speakers)),
    props: spec.props || [],
    setting: spec.setting || '',
    directorRunning: false,
    log: [],
  }

  for (const seed of spec.opening || []) {
    state.turns.push({
      n: state.turns.length + 1,
      speaker: seed.speaker,
      line: seed.line,
      ...(seed.action ? { action: seed.action } : {}),
      objectiveAtTime: state.speakers[seed.speaker].objective,
    })
  }

  while (state.turns.length < opts.turns) {
    const { turn, bids } = await nextTurn(state, opts)
    const round = { round: state.turns.length + 1, bids, won: turn?.speaker || null }
    state.log.push(round)
    opts.onRound?.(round)
    if (!turn) break
    state.turns.push(turn)
    maybeDirect(state, opts)
  }

  // Let a Director call that is still in flight land, so the record is whole —
  // and so the narration pass that follows does not queue behind it on a
  // server that serves one request at a time. With a 4,000-token budget and
  // thinking on, a Director call can outlast the half minute this used to wait.
  for (let i = 0; i < 1200 && state.directorRunning; i++) {
    await new Promise(settle => setTimeout(settle, 500))
  }
  return state
}
